url: https://courses.stolley.co
baseurl: /fwd/

timezone: America/Chicago

course:
  number: ITMD 361
  title: Fundamentals of Web Development
  uid: fwd
  tagline: >
    Write a course tagline in `_config.yml`
  term: Fall 2020
  # Set `days: ""` (empty string) for weekly/asynchronous classes
  days:
    - Monday
    - Wednesday

  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/4.0/
  instructor:
    honorific: Dr.
    name: Karl Stolley
    title: Professor
    full_title: Enter a full professional title in `_config.yml`
    url: https://stolley.co/
    github: https://github.com/karlstolley/
    email: kstolley@iit.edu
    office_hours: >
      Detail your office hours in `_config.yml`
  navigation:
    - label: Calendar
      href: "#this-week"
      id: cal
    - label: Projects
      href: "projects/#current"
      id: pro
    - label: Policies
      href: "policies/"
      id: pol
  css:
    font-url: "https://use.typekit.net/pig5ein.css"

collections_dir: syllabus

collections:
  weeks:
  projects:
  policies:
    # Rearrange the files listed here to change their order on the policies page.
    # To remove a section from the policies page, you *must* delete the file in the
    # /syllabus/_policies/ directory
    order:
      - description.md
      - goals.md
      - outcomes.md
      - objectives.md
      - books.md
      - materials.md
      - special-needs.md
      - participation.md
      - assignment-submission.md
      - late-work.md
      - grading-policy.md
      - grading-criteria.md
      - technology-policy.md
      - academic-integrity.md

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-open-course

exclude:
  - backstop_data
  - backstop.json
  - exe
  - lib
  - Rakefile
  - "*.gemspec"
